//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PredictiveAnalysis.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParentCustomer
    {
        public string ParentCustomerId { get; set; }
        public string ParentCustomerName { get; set; }
        public string HomePageURL { get; set; }
    }
}
