//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PredictiveAnalysis.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawData
    {
        public int Row { get; set; }
        public Nullable<double> CreditTerms { get; set; }
        public Nullable<double> DSO { get; set; }
        public Nullable<double> GrossProfit { get; set; }
        public Nullable<double> InventoryLocationAccuracy { get; set; }
        public Nullable<double> OnTimeDelivery { get; set; }
        public Nullable<double> OnTimeShipping { get; set; }
        public Nullable<double> ShippingAccuracy { get; set; }
        public Nullable<double> ThirdPartyTradeReceivables { get; set; }
        public Nullable<double> TotalNetRevenue { get; set; }
        public Nullable<double> Churn { get; set; }
    }
}
